### ISSUE TITLE
使用视频脚本下载，发生错误

### ISSUE THREAD

**Issue by kelso272** [sparrow629/Tumblr_Crawler#2]
E:\u>python v.py
Input url: http://\*\*.tumblr.com/
https://www.tumblr.com/video/**/
Traceback (most recent call last):
  File "v.py", line 79, in <module>
    getMP4(URL)
  File "v.py", line 46, in getMP4
    videourl = re.findall(videore, videohtml)[0]
IndexError: list index out of range

**Comment by sparrow629** [comment]
两个原因，一是可能原视频被删了，二是这个blog用了自己下载的的网页主题样式，匹配不到默认主题正则的规则。有能力的话针对当前css样式修改下正则规则就可以提取url了

**Comment by kelso272** [comment]
@sparrow629  视频应该有的，我用网页可以打开这个视频。如何根据当前css样式修改正则规则，是要修改某个函数吗？

**Comment by sparrow629** [comment]
根据网页源码视频url所在的位置的特征，修改reg_url 的匹配规则
