### ISSUE TITLE
大神可不可以根据博客名保存到单独的目录

### ISSUE THREAD

**Issue by weigeloveu** [sparrow629/Tumblr_Crawler#4]
1.比如说我同时下了 a 跟 b的博客，现在图片都是混在一起的，能不能分开保存。
2.比如说我今天抓了a博客 过一阵博客又更新了，是不是要重新抓

**Comment by sparrow629** [comment]
命名是根据博客名加序号排序的，按名称排序就自动分开了。

weigeloveu <notifications@github.com>于2017年9月11日 周一17:01写道：
